version: "3"
services:
  nginx:
    image: "hpehl/model-graph-nginx"
    ports:
      - "8080:80"
  wf9:
    image: "hpehl/model-graph-wildfly:9.0.2.Final"
    ports:
      - "7474:7474"
      - "7687:7687"
